spring.datasource.url=${DMS_DB_URL}
spring.datasource.username=${DMS_DB_USERNAME}
spring.datasource.password=${DMS_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.baseline-on-migrate=${DMS_FLYWAY_BASELINE_ON_MIGRATE:false}
spring.jpa.open-in-view=false
management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health,info